//priority: 200

onEvent('server.datapack.first', event => {
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/tc_parts.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyapple.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyarrows.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyblock.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anycards.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anycarts.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anycreateparts.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anycrops.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyengineer.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyfairylight.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyfishes.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyfood.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyindustrial.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anylogistics.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anymechanics.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anypotion.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyrails.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyrares_useables.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyrares_curio.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyredstone.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyseeds.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anystews.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/more_gems.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/more_metals.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/tc_parts.json', {})
	
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/druidic_loot.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/floral_loot.json', {})
	
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anytools/anytools1.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyarmor/anyarmor1.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anytools/anytools2.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyarmor/anyarmor2.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anytools/anytools3.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyarmor/anyarmor3.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anytools/anytools4.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyarmor/anyarmor4.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anytools/anytools5.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/anyarmor/anyarmor5.json', {})
	
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/affixgear1.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/affixgear2.json', {})
	event.addJson('kubejs:loot_tables/chests/loot_randomizer/affixgear3.json', {})
})