// priority: 700

global.disabledItems = [
		'cyclic:ender_pearl_mounted',
		
		'eidolon:sulfur',
		
		'bloodmagic:coalsand',

		'rftoolsbase:dimensionalshard_overworld', 
		'rftoolsbase:dimensionalshard_nether', 
		'rftoolsbase:dimensionalshard_end', 
		'rftoolsbase:dimensionalshard',

		'/inventorypets:feed_bag_new/',
		
		'refinedstorageaddons:wireless_crafting_grid',

		'/relics:.+_ingot/',
		'relics:flaming_amber_geode', 
		'relics:flaming_amber_dust', 
		'relics:chrysolite',
		
		'/immersiveengineering:plate_.+/',

		'create:copper_sheet', 
		'create:brass_sheet', 
		'create:iron_sheet', 
		'create:golden_sheet', 
		'createaddition:zinc_sheet',
		
		'forcecraft:spoils_bag', 
		'forcecraft:spoils_bag_t2', 
		'forcecraft:spoils_bag_t3', 
		'forcecraft:life_card', 
		'forcecraft:darkness_card', 
		'forcecraft:undeath_card',
		
		'/cyclic:soulstone/',
		
		'ob_core:chiseled_platinum_bricks', 
		'ob_core:platinum_bricks', 
		'ob_core:platinum_brick_stairs', 
		'ob_core:platinum_brick_slab', 
		'ob_core:platinum_brick_wall',
		
		'immersiveengineering:slab_coke',
		'immersiveengineering:coal_coke',
		'immersiveengineering:coke',

		'infernalexp:cooked_hogchop',
		'infernalexp:raw_hogchop',
		
		'relics:magic_mirror',
		
		'druidcraft:hellkiln', 
		'druidcraft:hellkiln_igniter', 
		'druidcraft:brightstone', 
		'druidcraft:tempered_fiery_glass', 
		'druidcraft:crushed_fiery_glass', 
		'druidcraft:brightstone', 
		'druidcraft:heart_of_blaze',
		'forbidden_arcanus:dragon_scale',
		'twilightforest:uncrafting_table',
		'forbidden_arcanus:wax',
		'kubejs:dummy_fluid_item',
		'kubejs:cc5_icon',
		'ob_core:sword_billet',
		'supplementaries:pancake',
		
		'ftbic:wind_mill',
		'ftbic:powered_furnace',
		'ftbic:iron_furnace',
		'ftbic:basic_generator',
		'buzzier_bees:honey_apple',
		'cyclic:apple_honey',
		
		'ironfurnaces:heater',
		'ironfurnaces:item_heater',

		'buildersaddition:large_candle', 
		'buildersaddition:large_soul_candle', 
		'buildersaddition:candle', 
		'buildersaddition:soul_candle',

		'createaddition:overcharged_casing',
		
		'infernalexp:basalt_iron_ore',

		'ob_core:platinum_bolt',

		'/statues:player_statue/',

		//wires
		'createaddition:copper_wire',
		'ftbic:copper_wire',
		'ftbic:aluminum_wire',
		'ftbic:gold_wire',

		//gears
		'titanium:gold_gear',
		'titanium:iron_gear',
		'titanium:diamond_gear',

		'/wyrmroost:platinum_helmet/',
		'/wyrmroost:platinum_chestplate/',
		'/wyrmroost:platinum_leggings/',
		'/wyrmroost:platinum_boots/',
		'/wyrmroost:platinum_sword/',

		'/dankstorage:.+to.+/',

		'ironchest:iron_to_gold_chest_upgrade',
		'ironchest:gold_to_diamond_chest_upgrade',
		'ironchest:copper_to_silver_chest_upgrade',
		'ironchest:silver_to_gold_chest_upgrade',
		'ironchest:copper_to_iron_chest_upgrade',
		'ironchest:diamond_to_crystal_chest_upgrade',
		'ironchest:wood_to_iron_chest_upgrade',
		'ironchest:wood_to_copper_chest_upgrade',
		'ironchest:diamond_to_obsidian_chest_upgrade',

		'metalbarrels:wood_to_iron',
		'metalbarrels:wood_to_silver',
		'metalbarrels:wood_to_gold',
		'metalbarrels:wood_to_diamond',
		'metalbarrels:wood_to_obsidian',
		'metalbarrels:wood_to_netherite',
		'metalbarrels:wood_to_crystal',

		'metalbarrels:copper_to_silver',
		'metalbarrels:copper_to_gold',
		'metalbarrels:copper_to_diamond',
		'metalbarrels:copper_to_obsidian',
		'metalbarrels:copper_to_crystal',

		'metalbarrels:iron_to_gold',
		'metalbarrels:iron_to_diamond',
		'metalbarrels:iron_to_obsidian',
		'metalbarrels:iron_to_crystal',
		'metalbarrels:silver_to_diamond',
		'metalbarrels:silver_to_obsidian',
		'metalbarrels:silver_to_crystal',
		'metalbarrels:gold_to_obsidian',
		'metalbarrels:gold_to_crystal',

		'#forge:iron_gear',

		'/gunswithoutroses:gold_gun/',

		'draconicevolution:generator',

		'calemiutils:sledgehammer_wood',
		'calemiutils:sledgehammer_stone',
		'calemiutils:sledgehammer_iron',
		'calemiutils:sledgehammer_gold',

		'gobber2:gobber2_ring_sunshine',
		'gobber2:gobber2_ring_curing',
		'gobber2:gobber2_ring_vision',
		'gobber2:gobber2_ring_repair',
		'gobber2:gobber2_ring_airwalking',
		'gobber2:gobber2_medallion_breathing',
		'gobber2:gobber2_medallion_hero',
		'gobber2:gobber2_staff_ensnarement',
		'gobber2:gobber2_ring_explorer',

		'cyclic:experience_food',
		'cyclic:peat_fuel',
		'cyclic:peat_fuel_enriched',
		'/cyclic:spawn_inspector/',
		'/cyclic:slingshot/',
		'cyclic:apple_ender',
		'cyclic:wireless_fluid',
		'cyclic:inventory_cake',
		'cyclic:fan_slab',
		'cyclic:rotator',
		'cyclic:detector_moon',
		'cyclic:detector_weather',
		'/cyclic:prospector/',
		'cyclic:ender_item_shelf',
		'cyclic:spikes_diamond',
		'cyclic:wireless_item',
		'cyclic:wireless_energy',
		'cyclic:chorus_spectral',
		'cyclic:chorus_flight',
		'/cyclic:storage_bag/',
		'cyclic:shearing',
		'cyclic:hopper_fluid',
		'cyclic:hopper_gold',
		'cyclic:hopper',
		'cyclic:anvil_void',
		'cyclic:sprinkler',

		'/cyclic:charm_longfall/',
		'/cyclic:charm_creeper/',
		'/cyclic:charm_stone/',
		'/cyclic:charm_antipotion/',
		'/cyclic:charm_invisible/',
		'/cyclic:charm_starvation/',
		'/cyclic:charm_venom/',
		'/cyclic:charm_water/',
		'/cyclic:charm_speed/',
		'/cyclic:charm_knockback_resistance/',
		'/cyclic:charm_luck/',
		'/cyclic:charm_attack_speed/',
		'/cyclic:charm_xp_speed/',
		'/cyclic:charm_stone/',

		'bountifulbaubles:potion_recall',

		'/forbidden_arcanus:bone_sword/',
		'/forbidden_arcanus:bone_pickaxe/',
		'/forbidden_arcanus:bone_axe/',
		'/forbidden_arcanus:bone_shovel/',
		'/forbidden_arcanus:bone_hoe/',

		'/calemiutils:sledgehammer_starlight/',
		'calemiutils:knob_starlight',

		'mctb:birch_crafting_table',
		'mctb:spruce_crafting_table',
		'mctb:acacia_crafting_table',
		'mctb:jungle_crafting_table',
		'mctb:dark_oak_crafting_table',
		'mctb:crimson_crafting_table',
		'mctb:warped_crafting_table',

		'securitycraft:inventory_scanner',
		'/securitycraft:codebreaker/',

		'outvoted:prismarine_rod',

		'occultism:iron_dust',
		'occultism:gold_dust',
		'occultism:copper_dust',
		'occultism:silver_dust',

		'industrialforegoing:mob_duplicator',

		'tinyredstone:silicon',
		'tinyredstone:silicon_compound',

		'forbidden_arcanus:dark_rune_bag',

		'extcaves:pebble_stone',
		'/extcaves:picker_stone/',
		'/extcaves:picker_flint/',
		'extcaves:plant_fiber',
		'extcaves:medicine_bandage',

		'inspirations:rope',

		'charm:gunpowder_block',

		'rftoolsbase:infused_diamond',
		'rftoolsbase:infused_enderpearl',

		'/betterendforge:iron_hammer/',
		'/betterendforge:golden_hammer/',

		'xreliquary:bat_wing',

		'/forbidden_arcanus:arcane_golden_sword/',
		'/forbidden_arcanus:arcane_golden_pickaxe/',
		'/forbidden_arcanus:arcane_golden_axe/',
		'/forbidden_arcanus:arcane_golden_shovel/',
		'/forbidden_arcanus:arcane_golden_hoe/',

		'/forbidden_arcanus:arcane_gold_helmet/',
		'/forbidden_arcanus:arcane_gold_chestplate/',
		'/forbidden_arcanus:arcane_gold_leggings/',
		'/forbidden_arcanus:arcane_gold_boots/',

		'metalbarrels:wood_to_copper',
		'metalbarrels:copper_to_iron',
		'metalbarrels:iron_to_silver',
		'metalbarrels:silver_to_gold',
		'metalbarrels:gold_to_diamond',
		'metalbarrels:diamond_to_obsidian',
		'metalbarrels:diamond_to_crystal',

		'engineersdecor:small_lab_furnace',
		'engineersdecor:small_electrical_furnace',
		'engineersdecor:small_mineral_smelter',
		'engineersdecor:small_solar_panel',

		'integrateddynamics:coal_generator',

		'ironfurnaces:item_spooky',
		'ironfurnaces:item_xmas',
		'ironfurnaces:upgrade_netherite',

		'/evilcraft:invigorating_pendant/',
		'/evilcraft:primed_pendant/',
		'evilcraft:eternal_water',
		'evilcraft:bucket_eternal_water',

		'autumnity:pumpkin_bread',

		'buildersaddition:crossrail',

		'/druidcraft:.+_bedroll/',
		'/druidcraft:travel_pack/',

		'charm:kiln',

		'rftoolsutility:syringe',
		'rftoolsutility:matter_beamer',
		'rftoolsutility:spawner',

		'byg:chain_plating',

		'forbidden_arcanus:spectral_eye_amulet',
		'forbidden_arcanus:boom_arrow',
		'forbidden_arcanus:rotten_leather',

		'industrialforegoing:mob_imprisonment_tool',

		'meetyourfight:spectres_eye',

		'/farmersdelight:golden_knife/',

		'/aquaculture:wooden_fillet_knife/',
		'/aquaculture:stone_fillet_knife/',
		'/aquaculture:iron_fillet_knife/',
		'/aquaculture:gold_fillet_knife/',
		'/aquaculture:diamond_fillet_knife/',

		'xreliquary:rod_of_lyssa',

		'#forge:dusts/constantan',
		'#forge:dusts/electrum',

		'powah:uraninite_raw_poor',
		'powah:uraninite_raw',
		'powah:uraninite_raw_dense',
		
		'bountifulbaubles:amulet_sin_empty',
		'/bountifulbaubles:gloves_digging_iron/',
		'/bountifulbaubles:gloves_digging_diamond/',
		'bountifulbaubles:broken_heart',
		'bountifulbaubles:phylactery_charm',
		'bountifulbaubles:water_candle',

		'supplementaries:stone_lamp',
		'supplementaries:sack',
		'supplementaries:hourglass',

		'druidcraft:woodcutter',

		'darkutils:ender_hopper',
		'darkutils:dark_glass',

		'druidcraft:knife',
		'/druidcraft:bone_.+/',

		'/mysticalworld:.+_knife/',
		'/mysticalworld:.+_spear/',

		'/iceandfire:armor_copper_metal_helmet/',
		'/iceandfire:armor_copper_metal_chestplate/',
		'/iceandfire:armor_copper_metal_leggings/',
		'/iceandfire:armor_copper_metal_boots/',
		'/iceandfire:copper_sword/',
		'/iceandfire:copper_pickaxe/',
		'/iceandfire:copper_axe/',
		'/iceandfire:copper_shovel/',
		'/iceandfire:copper_hoe/',
		'/iceandfire:armor_silver_metal_helmet/',
		'/iceandfire:armor_silver_metal_chestplate/',
		'/iceandfire:armor_silver_metal_leggings/',
		'/iceandfire:armor_silver_metal_boots/',
		'/iceandfire:silver_sword/',
		'/iceandfire:silver_pickaxe/',
		'/iceandfire:silver_axe/',
		'/iceandfire:silver_shovel/',
		'/iceandfire:silver_hoe/',

		'cyclic:generator_fuel',
		'cyclic:generator_food',
		'cyclic:generator_fluid',
		'cyclic:generator_item',
		'cyclic:packager',
		'cyclic:soil',
		'cyclic:peat_farm',
		'cyclic:solidifier',
		'cyclic:melter',
		'cyclic:placer',
		'cyclic:breaker',
		'cyclic:user',
		'cyclic:dropper',
		'cyclic:forester',
		'cyclic:miner',
		'cyclic:structure',
		'cyclic:harvester',
		'cyclic:collector',
		'cyclic:collector_fluid',
		'cyclic:placer_fluid',
		'cyclic:cask',
		'cyclic:computer_shape',
		'cyclic:eye_redstone',
		'cyclic:battery',
		'cyclic:peat_generator',
		'cyclic:peat_unbaked',
		'cyclic:peat_baked',
		'cyclic:apple_sprout',
		'cyclic:apple_sprout_diamond',
		'cyclic:apple_sprout_emerald',
		'cyclic:crate',
		'cyclic:clock',
		'cyclic:wireless_transmitter',
		'cyclic:wireless_receiver',
		'cyclic:plate_launch_redstone',
		'cyclic:plate_launch',
		'cyclic:detector_item',
		'cyclic:detector_entity',
		'cyclic:screen',
		'cyclic:uncrafter',
		'cyclic:disenchanter',
		'cyclic:fan',
		'cyclic:soundproofing',
		'cyclic:anvil',
		'cyclic:anvil_magma',
		'cyclic:beacon',
		'cyclic:tank',
		'cyclic:trash',
		'cyclic:crafter',
		'cyclic:unbreakable_block',
		'cyclic:unbreakable_reactive',
		'cyclic:conveyor',
		'cyclic:ender_shelf',
		'cyclic:ender_controller',
		'cyclic:workbench',
		'cyclic:experience_pylon',
		'cyclic:biomass',
		'/cyclic:mattock/',
		'/cyclic:sleeping_mat/',
		'/cyclic:shears_obsidian/',
		'/cyclic:shears_flint/',
		'/cyclic:scythe_.+/',
		'cyclic:lever_remote',
		'/cyclic:.+_scepter/',
		'cyclic:ender_bag',
		'/cyclic:spell_water/',
		'/cyclic:spell_ice/',
		'/cyclic:torch_launcher/',
		'/cyclic:charm_torch/',
		'/cyclic:charm_torch_cave/',
		'/cyclic:charm_home/',
		'/cyclic:charm_world/',
		'/cyclic:spelunker/',
		'cyclic:magic_net',
		'cyclic:tile_transporter_empty',
		'/cyclic:elevation_wand/',
		'/cyclic:teleport_wand/',
		'cyclic:settings_data',
		'cyclic:shape_data',
		'cyclic:storage_bag',
		'cyclic:crafting_bag',
		'cyclic:crafting_stick',
		'/cyclic:antimatter_wand/',
		'/cyclic:boomerang_.+/',
		'cyclic:scaffold_replace',
		'cyclic:scaffold_fragile',
		'cyclic:scaffold_responsive',
		'cyclic:spikes_iron',
		'cyclic:spikes_curse',
		'cyclic:spikes_fire',
		'cyclic:energy_pipe',
		'cyclic:item_pipe',
		'cyclic:fluid_pipe',
		'cyclic:cable_wrench',
		'/cyclic:glove_climb/',
		'/cyclic:flippers/',
		'/cyclic:antigravity/',
		'/cyclic:charm_void/',
		'/cyclic:charm_antidote/',
		'/cyclic:charm_fire/',
		'/cyclic:charm_wither/',
		'/cyclic:charm_ultimate/',
		'cyclic:carrot_ender',
		'cyclic:toxic_carrot',
		'/cyclic:.+_sword/',
		'/cyclic:.+_pickaxe/',
		'/cyclic:.+_axe/',
		'/cyclic:.+_shovel/',
		'/cyclic:.+_hoe/',
		'/cyclic:.+_helmet/',
		'/cyclic:.+_chestplate/',
		'/cyclic:.+_leggings/',
		'/cyclic:.+_boots/',
		'cyclic:heart',
		'cyclic:heart_empty',
		'/cyclic:wrench/',
		'/cyclic:ender_book/',

		'/chiselsandbits:chisel_stone/',
		'/chiselsandbits:chisel_gold/',

		'/engineerstools:crushing_hammer/',
		'/engineerstools:stimpack/',
		'/engineerstools:sleeping_bag/',
		'/engineerstools:diving_capsule/',
		'engineerstools:musli_bar_press',
		'engineerstools:charged_lapis_squeezer',
		'engineerstools:iron_grit',
		'engineerstools:gold_grit',

		'xreliquary:phoenix_down',

		'botania:ender_eye_block',

		'quark:feeding_trough',
		'quark:rope',

		'buildersaddition:iron_rod',

		'engineersdecor:metal_crafting_table',

		'pamhc2foodcore:cheeseitem',
		'pamhc2foodcore:chocolatebaritem',

		'betterendforge:crystalline_sulphur'
	];