onEvent('chest.loot_tables', event => {
	event.addChest('kubejs:loot_randomizer/anyarmor/anyarmor4', table => {
		table.addPool(pool => {
			pool.rolls = 1;
			Ingredient.of([
				'/.+helmet/', '/.+chestplate/', '/.+leggings/', '/.+boots/'
			]).filter(Ingredient.of([
				'@alexsmobs',
				'@apotheosis',
				'@aquaculture',
				'@aquamirae',
				'@ars_nouveau',
				'@atum',
				'@autumnity',
				'@betterendforge',
				'@bloodmagic',
				'@blue_skies',
				'@buddycards',
				'@ceramics',
				'@create',
				'@createplus',
				'@cyclic',
				'@desolation',
				'@draconicevolution',
				'@dungeons_mobs',
				'@dustrial_decor',
				'@eidolon',
				'@enigmaticlegacy',
				'@environmental',
				'@farlanders',
				'@forcecraft',
				'@ftbic',
				'@gaiadimension',
				'@gobber2',
				'@iceandfire',
				'@inventorypets',
				'@jellyfishing',
				'@malum',
				'@mana-and-artifice',
				'@materialis',
				'@mowziesmobs',
				'@mutantbeasts',
				'@mutantmore',
				'@naturesaura',
				'@nethers_exoticism',
				'@nourished_end',
				'@ob_core',
				'@occultism',
				'@omnis',
				'@outvoted',
				'@pneumaticcraft',
				'@psi',
				'@psipherals',
				'@rats',
				'@resourcefulbees',
				'@rootsclassic',
				'@sanguinearsenal',
				'@securitycraft',
				'@scuba_gear',
				'@tconstruct',
				'@theoneprobe',
				'@tropicraft',
				'@turtlemancy',
				'@twilightforest',
				'@undergarden',
				'@wyrmroost',
				'@xreliquary',
				'/.+alfsteel.+/',
				'/.+ametrine.+/',
				'/.+arcane_golden.+/',
				'/.+arcane.+/',
				'/.+bighorn.+/',
				'/.+bone.+/',
				'/.+book.+/',
				'/.+cactus.+/',
				'/.+cardboard.+/',
				'/.+chainmail.+/',
				'/.+chitin.+/',
				'/.+clay.+/',
				'/.+copper.+/',
				'/.+diving.+/',
				'/.+draco_arcanus.+/',
				'/.+drake.+/',
				'/.+egg/',
				'/.+elementium.+/',
				'/.+geode.+/',
				'/.+gold.+/',
				'/.+iron.+/',
				'/.+lead.+/',
				'/.+leather.+/',
				'/.+manasteel.+/',
				'/.+manaweave.+/',
				'/.+moonstone.+/',
				'/.+mortem.+/',
				'/.+netherite.+/',
				'/.+obsidian.+/',
				'/.+pendorite.+/',
				'/.+rusty.+/',
				'/.+scuba.+/',
				'/.+silver.+/',
				'/.+stone.+/',
				'/.+terrasteel.+/',
				'/.+tin.+/',
				'/.+tyr.+/',
				'/.+utheric.+/',
				'/.+wooden.+/',
				'/betterlands:horned_cap.+/',
				'/mysticalworld:beetle_.+/',
				'minecraft:turtle_helmet',
				'/botania:terra_.+/'
			]).not()).stacks.forEach(armor => {
				pool.addEntry({
					"type": "minecraft:item",
					"functions": [{
						"function": "minecraft:enchant_with_levels",
						"levels": {
							"min": 30,
							"max": 49
						}
					}],
					"name": armor.id
				})

			})
		})
		event.addChest('kubejs:loot_randomizer/anytools/anytools4', table => {
			table.addPool(pool => {
				pool.rolls = 1;
				Ingredient.of([
					'/.+sword/', '/.+axe/', '/.+shovel/'
				]).filter(Ingredient.of([
					'@additionalbanners',
					'@alexsmobs',
					'@apotheosis',
					'@aquamirae',
					'@aquaculture',
					'@ars_nouveau',
					'@astralsorcery',
					'@atum',
					'@betterendforge',
					'@bloodmagic',
					'@blue_skies',
					'@botaniaadditions',
					'@buddycards',
					'@createplus',
					'@cyclic',
					'@draconicevolution',
					'@dungeons_mobs',
					'@eidolon',
					'@enigmaticlegacy',
					'@evilcraft',
					'@extcaves',
					'@farlanders',
					'@forcecraft',
					'@ftbic',
					'@gaiadimension',
					'@gobber2',
					'@iceandfire',
					'@inventorypets',
					'@jellyfishing',
					'@malum',
					'@mana-and-artifice',
					'@materialis',
					'@mowziesmobs',
					'@mutantbeasts',
					'@mutantmore',
					'@naturesaura',
					'@nethers_exoticism',
					'@nourished_end',
					'@ob_core',
					'@occultism',
					'@omnis',
					'@outvoted',
					'@pneumaticcraft',
					'@psi',
					'@psipherals',
					'@quark',
					'@rats',
					'@resourcefulbees',
					'@rootsclassic',
					'@securitycraft',
					'@tconstruct',
					'@theoneprobe',
					'@tropicraft',
					'@turtlemancy',
					'@twilightforest',
					'@undergarden',
					'@wyrmroost',
					'@xreliquary',
					'/.+alfsteel.+/',
					'/.+arcane_golden.+/',
					'/.+bighorn.+/',
					'/.+bone.+/',
					'/.+book.+/',
					'/.+cactus.+/',
					'/.+clay.+/',
					'/.+copper.+/',
					'/.+draco_arcanus.+/',
					'/.+egg/',
					'/.+elementium.+/',
					'/.+geode.+/',
					'/.+golden.+/',
					'/.+gold.+/',
					'/.+iron.+/',
					'/.+lead.+/',
					'/.+leather.+/',
					'/.+manasteel.+/',
					'/.+moonstone.+/',
					'/.+netherite.+/',
					'/.+obsidian.+/',
					'/.+rusty.+/',
					'/.+silver.+/',
					'/.+stone.+/',
					'/.+terra.+/',
					'/.+terrasteel.+/',
					'/.+tin.+/',
					'/.+tyr.+/',
					'/.+utheric.+/',
					'/.+wooden.+/',
					'/botania:glass_pickaxe/',
					'/forbidden_arcanus:infernum_pickaxe/',
					'/forbidden_arcanus:slimec_pickaxe/',
					'botania:star_sword',
					'botania:thunder_sword',
					'/botania:terra_.+/'
				]).not()).stacks.forEach(weapon => {
					pool.addEntry({
						"type": "minecraft:item",
						"functions": [{
							"function": "minecraft:enchant_with_levels",
							"levels": {
								"min": 30,
								"max": 49
							}
						}],
						"name": weapon.id
					})
				})
			})
		})
	})
})